// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bubi.proto

#ifndef PROTOBUF_bubi_2eproto__INCLUDED
#define PROTOBUF_bubi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_bubi_2eproto();
void protobuf_AssignDesc_bubi_2eproto();
void protobuf_ShutdownFile_bubi_2eproto();

class bubiMsgHeader;
class bubiMsg;

// ===================================================================

class bubiMsgHeader : public ::google::protobuf::Message {
 public:
  bubiMsgHeader();
  virtual ~bubiMsgHeader();

  bubiMsgHeader(const bubiMsgHeader& from);

  inline bubiMsgHeader& operator=(const bubiMsgHeader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const bubiMsgHeader& default_instance();

  void Swap(bubiMsgHeader* other);

  // implements Message ----------------------------------------------

  bubiMsgHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const bubiMsgHeader& from);
  void MergeFrom(const bubiMsgHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string command = 1;
  inline bool has_command() const;
  inline void clear_command();
  static const int kCommandFieldNumber = 1;
  inline const ::std::string& command() const;
  inline void set_command(const ::std::string& value);
  inline void set_command(const char* value);
  inline void set_command(const char* value, size_t size);
  inline ::std::string* mutable_command();
  inline ::std::string* release_command();
  inline void set_allocated_command(::std::string* command);

  // required uint32 msgSize = 2;
  inline bool has_msgsize() const;
  inline void clear_msgsize();
  static const int kMsgSizeFieldNumber = 2;
  inline ::google::protobuf::uint32 msgsize() const;
  inline void set_msgsize(::google::protobuf::uint32 value);

  // optional uint32 checkSum = 3;
  inline bool has_checksum() const;
  inline void clear_checksum();
  static const int kCheckSumFieldNumber = 3;
  inline ::google::protobuf::uint32 checksum() const;
  inline void set_checksum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:protocol.bubiMsgHeader)
 private:
  inline void set_has_command();
  inline void clear_has_command();
  inline void set_has_msgsize();
  inline void clear_has_msgsize();
  inline void set_has_checksum();
  inline void clear_has_checksum();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* command_;
  ::google::protobuf::uint32 msgsize_;
  ::google::protobuf::uint32 checksum_;
  friend void  protobuf_AddDesc_bubi_2eproto();
  friend void protobuf_AssignDesc_bubi_2eproto();
  friend void protobuf_ShutdownFile_bubi_2eproto();

  void InitAsDefaultInstance();
  static bubiMsgHeader* default_instance_;
};
// -------------------------------------------------------------------

class bubiMsg : public ::google::protobuf::Message {
 public:
  bubiMsg();
  virtual ~bubiMsg();

  bubiMsg(const bubiMsg& from);

  inline bubiMsg& operator=(const bubiMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const bubiMsg& default_instance();

  void Swap(bubiMsg* other);

  // implements Message ----------------------------------------------

  bubiMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const bubiMsg& from);
  void MergeFrom(const bubiMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .protocol.bubiMsgHeader header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline const ::protocol::bubiMsgHeader& header() const;
  inline ::protocol::bubiMsgHeader* mutable_header();
  inline ::protocol::bubiMsgHeader* release_header();
  inline void set_allocated_header(::protocol::bubiMsgHeader* header);

  // required string data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:protocol.bubiMsg)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::protocol::bubiMsgHeader* header_;
  ::std::string* data_;
  friend void  protobuf_AddDesc_bubi_2eproto();
  friend void protobuf_AssignDesc_bubi_2eproto();
  friend void protobuf_ShutdownFile_bubi_2eproto();

  void InitAsDefaultInstance();
  static bubiMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// bubiMsgHeader

// required string command = 1;
inline bool bubiMsgHeader::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void bubiMsgHeader::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
inline void bubiMsgHeader::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void bubiMsgHeader::clear_command() {
  if (command_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_->clear();
  }
  clear_has_command();
}
inline const ::std::string& bubiMsgHeader::command() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.command)
  return *command_;
}
inline void bubiMsgHeader::set_command(const ::std::string& value) {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  command_->assign(value);
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.command)
}
inline void bubiMsgHeader::set_command(const char* value) {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  command_->assign(value);
  // @@protoc_insertion_point(field_set_char:protocol.bubiMsgHeader.command)
}
inline void bubiMsgHeader::set_command(const char* value, size_t size) {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  command_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protocol.bubiMsgHeader.command)
}
inline ::std::string* bubiMsgHeader::mutable_command() {
  set_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    command_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsgHeader.command)
  return command_;
}
inline ::std::string* bubiMsgHeader::release_command() {
  clear_has_command();
  if (command_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = command_;
    command_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void bubiMsgHeader::set_allocated_command(::std::string* command) {
  if (command_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete command_;
  }
  if (command) {
    set_has_command();
    command_ = command;
  } else {
    clear_has_command();
    command_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsgHeader.command)
}

// required uint32 msgSize = 2;
inline bool bubiMsgHeader::has_msgsize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void bubiMsgHeader::set_has_msgsize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void bubiMsgHeader::clear_has_msgsize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void bubiMsgHeader::clear_msgsize() {
  msgsize_ = 0u;
  clear_has_msgsize();
}
inline ::google::protobuf::uint32 bubiMsgHeader::msgsize() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.msgSize)
  return msgsize_;
}
inline void bubiMsgHeader::set_msgsize(::google::protobuf::uint32 value) {
  set_has_msgsize();
  msgsize_ = value;
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.msgSize)
}

// optional uint32 checkSum = 3;
inline bool bubiMsgHeader::has_checksum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void bubiMsgHeader::set_has_checksum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void bubiMsgHeader::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void bubiMsgHeader::clear_checksum() {
  checksum_ = 0u;
  clear_has_checksum();
}
inline ::google::protobuf::uint32 bubiMsgHeader::checksum() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.checkSum)
  return checksum_;
}
inline void bubiMsgHeader::set_checksum(::google::protobuf::uint32 value) {
  set_has_checksum();
  checksum_ = value;
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.checkSum)
}

// -------------------------------------------------------------------

// bubiMsg

// required .protocol.bubiMsgHeader header = 1;
inline bool bubiMsg::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void bubiMsg::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void bubiMsg::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void bubiMsg::clear_header() {
  if (header_ != NULL) header_->::protocol::bubiMsgHeader::Clear();
  clear_has_header();
}
inline const ::protocol::bubiMsgHeader& bubiMsg::header() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsg.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::protocol::bubiMsgHeader* bubiMsg::mutable_header() {
  set_has_header();
  if (header_ == NULL) header_ = new ::protocol::bubiMsgHeader;
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsg.header)
  return header_;
}
inline ::protocol::bubiMsgHeader* bubiMsg::release_header() {
  clear_has_header();
  ::protocol::bubiMsgHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline void bubiMsg::set_allocated_header(::protocol::bubiMsgHeader* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsg.header)
}

// required string data = 2;
inline bool bubiMsg::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void bubiMsg::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void bubiMsg::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void bubiMsg::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& bubiMsg::data() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsg.data)
  return *data_;
}
inline void bubiMsg::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:protocol.bubiMsg.data)
}
inline void bubiMsg::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:protocol.bubiMsg.data)
}
inline void bubiMsg::set_data(const char* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protocol.bubiMsg.data)
}
inline ::std::string* bubiMsg::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsg.data)
  return data_;
}
inline ::std::string* bubiMsg::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void bubiMsg::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsg.data)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_bubi_2eproto__INCLUDED
