// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "transaction.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bubi {

namespace {

const ::google::protobuf::Descriptor* Transaction_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Transaction_reflection_ = NULL;
const ::google::protobuf::Descriptor* Account_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Account_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_transaction_2eproto() {
  protobuf_AddDesc_transaction_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "transaction.proto");
  GOOGLE_CHECK(file != NULL);
  Transaction_descriptor_ = file->message_type(0);
  static const int Transaction_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transaction, source_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transaction, destination_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transaction, payment_amount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transaction, last_ledger_hash_),
  };
  Transaction_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Transaction_descriptor_,
      Transaction::default_instance_,
      Transaction_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transaction, _has_bits_[0]),
      -1,
      -1,
      sizeof(Transaction),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transaction, _internal_metadata_),
      -1);
  Account_descriptor_ = file->message_type(1);
  static const int Account_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Account, account_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Account, account_balance_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Account, previous_ledger_hash_),
  };
  Account_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Account_descriptor_,
      Account::default_instance_,
      Account_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Account, _has_bits_[0]),
      -1,
      -1,
      sizeof(Account),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Account, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_transaction_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Transaction_descriptor_, &Transaction::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Account_descriptor_, &Account::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_transaction_2eproto() {
  delete Transaction::default_instance_;
  delete Transaction_reflection_;
  delete Account::default_instance_;
  delete Account_reflection_;
}

void protobuf_AddDesc_transaction_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021transaction.proto\022\004bubi\"t\n\013Transaction"
    "\022\026\n\016source_address\030\001 \002(\t\022\033\n\023destination_"
    "address\030\002 \002(\t\022\026\n\016payment_amount\030\003 \001(\001\022\030\n"
    "\020last_ledger_hash\030\004 \002(\t\"Y\n\007Account\022\027\n\017ac"
    "count_address\030\001 \002(\t\022\027\n\017account_balance\030\002"
    " \002(\001\022\034\n\024previous_ledger_hash\030\003 \002(\t", 234);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "transaction.proto", &protobuf_RegisterTypes);
  Transaction::default_instance_ = new Transaction();
  Account::default_instance_ = new Account();
  Transaction::default_instance_->InitAsDefaultInstance();
  Account::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_transaction_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_transaction_2eproto {
  StaticDescriptorInitializer_transaction_2eproto() {
    protobuf_AddDesc_transaction_2eproto();
  }
} static_descriptor_initializer_transaction_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int Transaction::kSourceAddressFieldNumber;
const int Transaction::kDestinationAddressFieldNumber;
const int Transaction::kPaymentAmountFieldNumber;
const int Transaction::kLastLedgerHashFieldNumber;
#endif  // !_MSC_VER

Transaction::Transaction()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bubi.Transaction)
}

void Transaction::InitAsDefaultInstance() {
}

Transaction::Transaction(const Transaction& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bubi.Transaction)
}

void Transaction::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  source_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destination_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payment_amount_ = 0;
  last_ledger_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Transaction::~Transaction() {
  // @@protoc_insertion_point(destructor:bubi.Transaction)
  SharedDtor();
}

void Transaction::SharedDtor() {
  source_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destination_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  last_ledger_hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Transaction::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Transaction::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Transaction_descriptor_;
}

const Transaction& Transaction::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_transaction_2eproto();
  return *default_instance_;
}

Transaction* Transaction::default_instance_ = NULL;

Transaction* Transaction::New(::google::protobuf::Arena* arena) const {
  Transaction* n = new Transaction;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Transaction::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    if (has_source_address()) {
      source_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_destination_address()) {
      destination_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    payment_amount_ = 0;
    if (has_last_ledger_hash()) {
      last_ledger_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Transaction::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bubi.Transaction)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string source_address = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_source_address()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->source_address().data(), this->source_address().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bubi.Transaction.source_address");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_destination_address;
        break;
      }

      // required string destination_address = 2;
      case 2: {
        if (tag == 18) {
         parse_destination_address:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_destination_address()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->destination_address().data(), this->destination_address().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bubi.Transaction.destination_address");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_payment_amount;
        break;
      }

      // optional double payment_amount = 3;
      case 3: {
        if (tag == 25) {
         parse_payment_amount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &payment_amount_)));
          set_has_payment_amount();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_last_ledger_hash;
        break;
      }

      // required string last_ledger_hash = 4;
      case 4: {
        if (tag == 34) {
         parse_last_ledger_hash:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_last_ledger_hash()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->last_ledger_hash().data(), this->last_ledger_hash().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bubi.Transaction.last_ledger_hash");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bubi.Transaction)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bubi.Transaction)
  return false;
#undef DO_
}

void Transaction::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bubi.Transaction)
  // required string source_address = 1;
  if (has_source_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->source_address().data(), this->source_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Transaction.source_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->source_address(), output);
  }

  // required string destination_address = 2;
  if (has_destination_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->destination_address().data(), this->destination_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Transaction.destination_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->destination_address(), output);
  }

  // optional double payment_amount = 3;
  if (has_payment_amount()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->payment_amount(), output);
  }

  // required string last_ledger_hash = 4;
  if (has_last_ledger_hash()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->last_ledger_hash().data(), this->last_ledger_hash().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Transaction.last_ledger_hash");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->last_ledger_hash(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:bubi.Transaction)
}

::google::protobuf::uint8* Transaction::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:bubi.Transaction)
  // required string source_address = 1;
  if (has_source_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->source_address().data(), this->source_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Transaction.source_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->source_address(), target);
  }

  // required string destination_address = 2;
  if (has_destination_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->destination_address().data(), this->destination_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Transaction.destination_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->destination_address(), target);
  }

  // optional double payment_amount = 3;
  if (has_payment_amount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->payment_amount(), target);
  }

  // required string last_ledger_hash = 4;
  if (has_last_ledger_hash()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->last_ledger_hash().data(), this->last_ledger_hash().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Transaction.last_ledger_hash");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->last_ledger_hash(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bubi.Transaction)
  return target;
}

int Transaction::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_source_address()) {
    // required string source_address = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->source_address());
  }

  if (has_destination_address()) {
    // required string destination_address = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->destination_address());
  }

  if (has_last_ledger_hash()) {
    // required string last_ledger_hash = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->last_ledger_hash());
  }

  return total_size;
}
int Transaction::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000b) ^ 0x0000000b) == 0) {  // All required fields are present.
    // required string source_address = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->source_address());

    // required string destination_address = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->destination_address());

    // required string last_ledger_hash = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->last_ledger_hash());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional double payment_amount = 3;
  if (has_payment_amount()) {
    total_size += 1 + 8;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Transaction::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Transaction* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Transaction*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Transaction::MergeFrom(const Transaction& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_source_address()) {
      set_has_source_address();
      source_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.source_address_);
    }
    if (from.has_destination_address()) {
      set_has_destination_address();
      destination_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destination_address_);
    }
    if (from.has_payment_amount()) {
      set_payment_amount(from.payment_amount());
    }
    if (from.has_last_ledger_hash()) {
      set_has_last_ledger_hash();
      last_ledger_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.last_ledger_hash_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Transaction::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Transaction::CopyFrom(const Transaction& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transaction::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000b) != 0x0000000b) return false;

  return true;
}

void Transaction::Swap(Transaction* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Transaction::InternalSwap(Transaction* other) {
  source_address_.Swap(&other->source_address_);
  destination_address_.Swap(&other->destination_address_);
  std::swap(payment_amount_, other->payment_amount_);
  last_ledger_hash_.Swap(&other->last_ledger_hash_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Transaction::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Transaction_descriptor_;
  metadata.reflection = Transaction_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Transaction

// required string source_address = 1;
 bool Transaction::has_source_address() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void Transaction::set_has_source_address() {
  _has_bits_[0] |= 0x00000001u;
}
 void Transaction::clear_has_source_address() {
  _has_bits_[0] &= ~0x00000001u;
}
 void Transaction::clear_source_address() {
  source_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_source_address();
}
 const ::std::string& Transaction::source_address() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.source_address)
  return source_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transaction::set_source_address(const ::std::string& value) {
  set_has_source_address();
  source_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Transaction.source_address)
}
 void Transaction::set_source_address(const char* value) {
  set_has_source_address();
  source_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Transaction.source_address)
}
 void Transaction::set_source_address(const char* value, size_t size) {
  set_has_source_address();
  source_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Transaction.source_address)
}
 ::std::string* Transaction::mutable_source_address() {
  set_has_source_address();
  // @@protoc_insertion_point(field_mutable:bubi.Transaction.source_address)
  return source_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Transaction::release_source_address() {
  clear_has_source_address();
  return source_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transaction::set_allocated_source_address(::std::string* source_address) {
  if (source_address != NULL) {
    set_has_source_address();
  } else {
    clear_has_source_address();
  }
  source_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_address);
  // @@protoc_insertion_point(field_set_allocated:bubi.Transaction.source_address)
}

// required string destination_address = 2;
 bool Transaction::has_destination_address() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
 void Transaction::set_has_destination_address() {
  _has_bits_[0] |= 0x00000002u;
}
 void Transaction::clear_has_destination_address() {
  _has_bits_[0] &= ~0x00000002u;
}
 void Transaction::clear_destination_address() {
  destination_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_destination_address();
}
 const ::std::string& Transaction::destination_address() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.destination_address)
  return destination_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transaction::set_destination_address(const ::std::string& value) {
  set_has_destination_address();
  destination_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Transaction.destination_address)
}
 void Transaction::set_destination_address(const char* value) {
  set_has_destination_address();
  destination_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Transaction.destination_address)
}
 void Transaction::set_destination_address(const char* value, size_t size) {
  set_has_destination_address();
  destination_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Transaction.destination_address)
}
 ::std::string* Transaction::mutable_destination_address() {
  set_has_destination_address();
  // @@protoc_insertion_point(field_mutable:bubi.Transaction.destination_address)
  return destination_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Transaction::release_destination_address() {
  clear_has_destination_address();
  return destination_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transaction::set_allocated_destination_address(::std::string* destination_address) {
  if (destination_address != NULL) {
    set_has_destination_address();
  } else {
    clear_has_destination_address();
  }
  destination_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destination_address);
  // @@protoc_insertion_point(field_set_allocated:bubi.Transaction.destination_address)
}

// optional double payment_amount = 3;
 bool Transaction::has_payment_amount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
 void Transaction::set_has_payment_amount() {
  _has_bits_[0] |= 0x00000004u;
}
 void Transaction::clear_has_payment_amount() {
  _has_bits_[0] &= ~0x00000004u;
}
 void Transaction::clear_payment_amount() {
  payment_amount_ = 0;
  clear_has_payment_amount();
}
 double Transaction::payment_amount() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.payment_amount)
  return payment_amount_;
}
 void Transaction::set_payment_amount(double value) {
  set_has_payment_amount();
  payment_amount_ = value;
  // @@protoc_insertion_point(field_set:bubi.Transaction.payment_amount)
}

// required string last_ledger_hash = 4;
 bool Transaction::has_last_ledger_hash() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
 void Transaction::set_has_last_ledger_hash() {
  _has_bits_[0] |= 0x00000008u;
}
 void Transaction::clear_has_last_ledger_hash() {
  _has_bits_[0] &= ~0x00000008u;
}
 void Transaction::clear_last_ledger_hash() {
  last_ledger_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_last_ledger_hash();
}
 const ::std::string& Transaction::last_ledger_hash() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.last_ledger_hash)
  return last_ledger_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transaction::set_last_ledger_hash(const ::std::string& value) {
  set_has_last_ledger_hash();
  last_ledger_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Transaction.last_ledger_hash)
}
 void Transaction::set_last_ledger_hash(const char* value) {
  set_has_last_ledger_hash();
  last_ledger_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Transaction.last_ledger_hash)
}
 void Transaction::set_last_ledger_hash(const char* value, size_t size) {
  set_has_last_ledger_hash();
  last_ledger_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Transaction.last_ledger_hash)
}
 ::std::string* Transaction::mutable_last_ledger_hash() {
  set_has_last_ledger_hash();
  // @@protoc_insertion_point(field_mutable:bubi.Transaction.last_ledger_hash)
  return last_ledger_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Transaction::release_last_ledger_hash() {
  clear_has_last_ledger_hash();
  return last_ledger_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Transaction::set_allocated_last_ledger_hash(::std::string* last_ledger_hash) {
  if (last_ledger_hash != NULL) {
    set_has_last_ledger_hash();
  } else {
    clear_has_last_ledger_hash();
  }
  last_ledger_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), last_ledger_hash);
  // @@protoc_insertion_point(field_set_allocated:bubi.Transaction.last_ledger_hash)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int Account::kAccountAddressFieldNumber;
const int Account::kAccountBalanceFieldNumber;
const int Account::kPreviousLedgerHashFieldNumber;
#endif  // !_MSC_VER

Account::Account()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bubi.Account)
}

void Account::InitAsDefaultInstance() {
}

Account::Account(const Account& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bubi.Account)
}

void Account::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  account_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_balance_ = 0;
  previous_ledger_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Account::~Account() {
  // @@protoc_insertion_point(destructor:bubi.Account)
  SharedDtor();
}

void Account::SharedDtor() {
  account_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  previous_ledger_hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Account::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Account::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Account_descriptor_;
}

const Account& Account::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_transaction_2eproto();
  return *default_instance_;
}

Account* Account::default_instance_ = NULL;

Account* Account::New(::google::protobuf::Arena* arena) const {
  Account* n = new Account;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Account::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_account_address()) {
      account_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    account_balance_ = 0;
    if (has_previous_ledger_hash()) {
      previous_ledger_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Account::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bubi.Account)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string account_address = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account_address()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->account_address().data(), this->account_address().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bubi.Account.account_address");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_account_balance;
        break;
      }

      // required double account_balance = 2;
      case 2: {
        if (tag == 17) {
         parse_account_balance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &account_balance_)));
          set_has_account_balance();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_previous_ledger_hash;
        break;
      }

      // required string previous_ledger_hash = 3;
      case 3: {
        if (tag == 26) {
         parse_previous_ledger_hash:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_previous_ledger_hash()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->previous_ledger_hash().data(), this->previous_ledger_hash().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bubi.Account.previous_ledger_hash");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bubi.Account)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bubi.Account)
  return false;
#undef DO_
}

void Account::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bubi.Account)
  // required string account_address = 1;
  if (has_account_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->account_address().data(), this->account_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Account.account_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->account_address(), output);
  }

  // required double account_balance = 2;
  if (has_account_balance()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->account_balance(), output);
  }

  // required string previous_ledger_hash = 3;
  if (has_previous_ledger_hash()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->previous_ledger_hash().data(), this->previous_ledger_hash().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Account.previous_ledger_hash");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->previous_ledger_hash(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:bubi.Account)
}

::google::protobuf::uint8* Account::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:bubi.Account)
  // required string account_address = 1;
  if (has_account_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->account_address().data(), this->account_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Account.account_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->account_address(), target);
  }

  // required double account_balance = 2;
  if (has_account_balance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->account_balance(), target);
  }

  // required string previous_ledger_hash = 3;
  if (has_previous_ledger_hash()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->previous_ledger_hash().data(), this->previous_ledger_hash().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bubi.Account.previous_ledger_hash");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->previous_ledger_hash(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bubi.Account)
  return target;
}

int Account::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_account_address()) {
    // required string account_address = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account_address());
  }

  if (has_account_balance()) {
    // required double account_balance = 2;
    total_size += 1 + 8;
  }

  if (has_previous_ledger_hash()) {
    // required string previous_ledger_hash = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->previous_ledger_hash());
  }

  return total_size;
}
int Account::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string account_address = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account_address());

    // required double account_balance = 2;
    total_size += 1 + 8;

    // required string previous_ledger_hash = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->previous_ledger_hash());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Account::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Account* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Account*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Account::MergeFrom(const Account& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_account_address()) {
      set_has_account_address();
      account_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_address_);
    }
    if (from.has_account_balance()) {
      set_account_balance(from.account_balance());
    }
    if (from.has_previous_ledger_hash()) {
      set_has_previous_ledger_hash();
      previous_ledger_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.previous_ledger_hash_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Account::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Account::CopyFrom(const Account& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Account::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void Account::Swap(Account* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Account::InternalSwap(Account* other) {
  account_address_.Swap(&other->account_address_);
  std::swap(account_balance_, other->account_balance_);
  previous_ledger_hash_.Swap(&other->previous_ledger_hash_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Account::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Account_descriptor_;
  metadata.reflection = Account_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Account

// required string account_address = 1;
 bool Account::has_account_address() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void Account::set_has_account_address() {
  _has_bits_[0] |= 0x00000001u;
}
 void Account::clear_has_account_address() {
  _has_bits_[0] &= ~0x00000001u;
}
 void Account::clear_account_address() {
  account_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_account_address();
}
 const ::std::string& Account::account_address() const {
  // @@protoc_insertion_point(field_get:bubi.Account.account_address)
  return account_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Account::set_account_address(const ::std::string& value) {
  set_has_account_address();
  account_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Account.account_address)
}
 void Account::set_account_address(const char* value) {
  set_has_account_address();
  account_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Account.account_address)
}
 void Account::set_account_address(const char* value, size_t size) {
  set_has_account_address();
  account_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Account.account_address)
}
 ::std::string* Account::mutable_account_address() {
  set_has_account_address();
  // @@protoc_insertion_point(field_mutable:bubi.Account.account_address)
  return account_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Account::release_account_address() {
  clear_has_account_address();
  return account_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Account::set_allocated_account_address(::std::string* account_address) {
  if (account_address != NULL) {
    set_has_account_address();
  } else {
    clear_has_account_address();
  }
  account_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_address);
  // @@protoc_insertion_point(field_set_allocated:bubi.Account.account_address)
}

// required double account_balance = 2;
 bool Account::has_account_balance() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
 void Account::set_has_account_balance() {
  _has_bits_[0] |= 0x00000002u;
}
 void Account::clear_has_account_balance() {
  _has_bits_[0] &= ~0x00000002u;
}
 void Account::clear_account_balance() {
  account_balance_ = 0;
  clear_has_account_balance();
}
 double Account::account_balance() const {
  // @@protoc_insertion_point(field_get:bubi.Account.account_balance)
  return account_balance_;
}
 void Account::set_account_balance(double value) {
  set_has_account_balance();
  account_balance_ = value;
  // @@protoc_insertion_point(field_set:bubi.Account.account_balance)
}

// required string previous_ledger_hash = 3;
 bool Account::has_previous_ledger_hash() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
 void Account::set_has_previous_ledger_hash() {
  _has_bits_[0] |= 0x00000004u;
}
 void Account::clear_has_previous_ledger_hash() {
  _has_bits_[0] &= ~0x00000004u;
}
 void Account::clear_previous_ledger_hash() {
  previous_ledger_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_previous_ledger_hash();
}
 const ::std::string& Account::previous_ledger_hash() const {
  // @@protoc_insertion_point(field_get:bubi.Account.previous_ledger_hash)
  return previous_ledger_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Account::set_previous_ledger_hash(const ::std::string& value) {
  set_has_previous_ledger_hash();
  previous_ledger_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Account.previous_ledger_hash)
}
 void Account::set_previous_ledger_hash(const char* value) {
  set_has_previous_ledger_hash();
  previous_ledger_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Account.previous_ledger_hash)
}
 void Account::set_previous_ledger_hash(const char* value, size_t size) {
  set_has_previous_ledger_hash();
  previous_ledger_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Account.previous_ledger_hash)
}
 ::std::string* Account::mutable_previous_ledger_hash() {
  set_has_previous_ledger_hash();
  // @@protoc_insertion_point(field_mutable:bubi.Account.previous_ledger_hash)
  return previous_ledger_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Account::release_previous_ledger_hash() {
  clear_has_previous_ledger_hash();
  return previous_ledger_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Account::set_allocated_previous_ledger_hash(::std::string* previous_ledger_hash) {
  if (previous_ledger_hash != NULL) {
    set_has_previous_ledger_hash();
  } else {
    clear_has_previous_ledger_hash();
  }
  previous_ledger_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), previous_ledger_hash);
  // @@protoc_insertion_point(field_set_allocated:bubi.Account.previous_ledger_hash)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace bubi

// @@protoc_insertion_point(global_scope)
