// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

#ifndef PROTOBUF_transaction_2eproto__INCLUDED
#define PROTOBUF_transaction_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace bubi {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_transaction_2eproto();
void protobuf_AssignDesc_transaction_2eproto();
void protobuf_ShutdownFile_transaction_2eproto();

class Transaction;
class Account;

// ===================================================================

class Transaction : public ::google::protobuf::Message {
 public:
  Transaction();
  virtual ~Transaction();

  Transaction(const Transaction& from);

  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Transaction& default_instance();

  void Swap(Transaction* other);

  // implements Message ----------------------------------------------

  inline Transaction* New() const { return New(NULL); }

  Transaction* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Transaction& from);
  void MergeFrom(const Transaction& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Transaction* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string source_address = 1;
  bool has_source_address() const;
  void clear_source_address();
  static const int kSourceAddressFieldNumber = 1;
  const ::std::string& source_address() const;
  void set_source_address(const ::std::string& value);
  void set_source_address(const char* value);
  void set_source_address(const char* value, size_t size);
  ::std::string* mutable_source_address();
  ::std::string* release_source_address();
  void set_allocated_source_address(::std::string* source_address);

  // required string destination_address = 2;
  bool has_destination_address() const;
  void clear_destination_address();
  static const int kDestinationAddressFieldNumber = 2;
  const ::std::string& destination_address() const;
  void set_destination_address(const ::std::string& value);
  void set_destination_address(const char* value);
  void set_destination_address(const char* value, size_t size);
  ::std::string* mutable_destination_address();
  ::std::string* release_destination_address();
  void set_allocated_destination_address(::std::string* destination_address);

  // optional double payment_amount = 3;
  bool has_payment_amount() const;
  void clear_payment_amount();
  static const int kPaymentAmountFieldNumber = 3;
  double payment_amount() const;
  void set_payment_amount(double value);

  // required uint32 source_previous_ledger_seq = 4;
  bool has_source_previous_ledger_seq() const;
  void clear_source_previous_ledger_seq();
  static const int kSourcePreviousLedgerSeqFieldNumber = 4;
  ::google::protobuf::uint32 source_previous_ledger_seq() const;
  void set_source_previous_ledger_seq(::google::protobuf::uint32 value);

  // required string source_previous_tx_hash = 5;
  bool has_source_previous_tx_hash() const;
  void clear_source_previous_tx_hash();
  static const int kSourcePreviousTxHashFieldNumber = 5;
  const ::std::string& source_previous_tx_hash() const;
  void set_source_previous_tx_hash(const ::std::string& value);
  void set_source_previous_tx_hash(const char* value);
  void set_source_previous_tx_hash(const char* value, size_t size);
  ::std::string* mutable_source_previous_tx_hash();
  ::std::string* release_source_previous_tx_hash();
  void set_allocated_source_previous_tx_hash(::std::string* source_previous_tx_hash);

  // required uint32 destination_previous_ledger_seq = 6;
  bool has_destination_previous_ledger_seq() const;
  void clear_destination_previous_ledger_seq();
  static const int kDestinationPreviousLedgerSeqFieldNumber = 6;
  ::google::protobuf::uint32 destination_previous_ledger_seq() const;
  void set_destination_previous_ledger_seq(::google::protobuf::uint32 value);

  // required string destination_previous_tx_hash = 7;
  bool has_destination_previous_tx_hash() const;
  void clear_destination_previous_tx_hash();
  static const int kDestinationPreviousTxHashFieldNumber = 7;
  const ::std::string& destination_previous_tx_hash() const;
  void set_destination_previous_tx_hash(const ::std::string& value);
  void set_destination_previous_tx_hash(const char* value);
  void set_destination_previous_tx_hash(const char* value, size_t size);
  ::std::string* mutable_destination_previous_tx_hash();
  ::std::string* release_destination_previous_tx_hash();
  void set_allocated_destination_previous_tx_hash(::std::string* destination_previous_tx_hash);

  // @@protoc_insertion_point(class_scope:bubi.Transaction)
 private:
  inline void set_has_source_address();
  inline void clear_has_source_address();
  inline void set_has_destination_address();
  inline void clear_has_destination_address();
  inline void set_has_payment_amount();
  inline void clear_has_payment_amount();
  inline void set_has_source_previous_ledger_seq();
  inline void clear_has_source_previous_ledger_seq();
  inline void set_has_source_previous_tx_hash();
  inline void clear_has_source_previous_tx_hash();
  inline void set_has_destination_previous_ledger_seq();
  inline void clear_has_destination_previous_ledger_seq();
  inline void set_has_destination_previous_tx_hash();
  inline void clear_has_destination_previous_tx_hash();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr source_address_;
  ::google::protobuf::internal::ArenaStringPtr destination_address_;
  double payment_amount_;
  ::google::protobuf::internal::ArenaStringPtr source_previous_tx_hash_;
  ::google::protobuf::uint32 source_previous_ledger_seq_;
  ::google::protobuf::uint32 destination_previous_ledger_seq_;
  ::google::protobuf::internal::ArenaStringPtr destination_previous_tx_hash_;
  friend void  protobuf_AddDesc_transaction_2eproto();
  friend void protobuf_AssignDesc_transaction_2eproto();
  friend void protobuf_ShutdownFile_transaction_2eproto();

  void InitAsDefaultInstance();
  static Transaction* default_instance_;
};
// -------------------------------------------------------------------

class Account : public ::google::protobuf::Message {
 public:
  Account();
  virtual ~Account();

  Account(const Account& from);

  inline Account& operator=(const Account& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Account& default_instance();

  void Swap(Account* other);

  // implements Message ----------------------------------------------

  inline Account* New() const { return New(NULL); }

  Account* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Account& from);
  void MergeFrom(const Account& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Account* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string account_address = 1;
  bool has_account_address() const;
  void clear_account_address();
  static const int kAccountAddressFieldNumber = 1;
  const ::std::string& account_address() const;
  void set_account_address(const ::std::string& value);
  void set_account_address(const char* value);
  void set_account_address(const char* value, size_t size);
  ::std::string* mutable_account_address();
  ::std::string* release_account_address();
  void set_allocated_account_address(::std::string* account_address);

  // required double account_balance = 2;
  bool has_account_balance() const;
  void clear_account_balance();
  static const int kAccountBalanceFieldNumber = 2;
  double account_balance() const;
  void set_account_balance(double value);

  // required uint32 previous_ledger_seq = 3;
  bool has_previous_ledger_seq() const;
  void clear_previous_ledger_seq();
  static const int kPreviousLedgerSeqFieldNumber = 3;
  ::google::protobuf::uint32 previous_ledger_seq() const;
  void set_previous_ledger_seq(::google::protobuf::uint32 value);

  // required string previous_tx_hash = 4;
  bool has_previous_tx_hash() const;
  void clear_previous_tx_hash();
  static const int kPreviousTxHashFieldNumber = 4;
  const ::std::string& previous_tx_hash() const;
  void set_previous_tx_hash(const ::std::string& value);
  void set_previous_tx_hash(const char* value);
  void set_previous_tx_hash(const char* value, size_t size);
  ::std::string* mutable_previous_tx_hash();
  ::std::string* release_previous_tx_hash();
  void set_allocated_previous_tx_hash(::std::string* previous_tx_hash);

  // @@protoc_insertion_point(class_scope:bubi.Account)
 private:
  inline void set_has_account_address();
  inline void clear_has_account_address();
  inline void set_has_account_balance();
  inline void clear_has_account_balance();
  inline void set_has_previous_ledger_seq();
  inline void clear_has_previous_ledger_seq();
  inline void set_has_previous_tx_hash();
  inline void clear_has_previous_tx_hash();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr account_address_;
  double account_balance_;
  ::google::protobuf::internal::ArenaStringPtr previous_tx_hash_;
  ::google::protobuf::uint32 previous_ledger_seq_;
  friend void  protobuf_AddDesc_transaction_2eproto();
  friend void protobuf_AssignDesc_transaction_2eproto();
  friend void protobuf_ShutdownFile_transaction_2eproto();

  void InitAsDefaultInstance();
  static Account* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Transaction

// required string source_address = 1;
inline bool Transaction::has_source_address() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Transaction::set_has_source_address() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Transaction::clear_has_source_address() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Transaction::clear_source_address() {
  source_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_source_address();
}
inline const ::std::string& Transaction::source_address() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.source_address)
  return source_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_source_address(const ::std::string& value) {
  set_has_source_address();
  source_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Transaction.source_address)
}
inline void Transaction::set_source_address(const char* value) {
  set_has_source_address();
  source_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Transaction.source_address)
}
inline void Transaction::set_source_address(const char* value, size_t size) {
  set_has_source_address();
  source_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Transaction.source_address)
}
inline ::std::string* Transaction::mutable_source_address() {
  set_has_source_address();
  // @@protoc_insertion_point(field_mutable:bubi.Transaction.source_address)
  return source_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Transaction::release_source_address() {
  clear_has_source_address();
  return source_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_allocated_source_address(::std::string* source_address) {
  if (source_address != NULL) {
    set_has_source_address();
  } else {
    clear_has_source_address();
  }
  source_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_address);
  // @@protoc_insertion_point(field_set_allocated:bubi.Transaction.source_address)
}

// required string destination_address = 2;
inline bool Transaction::has_destination_address() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Transaction::set_has_destination_address() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Transaction::clear_has_destination_address() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Transaction::clear_destination_address() {
  destination_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_destination_address();
}
inline const ::std::string& Transaction::destination_address() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.destination_address)
  return destination_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_destination_address(const ::std::string& value) {
  set_has_destination_address();
  destination_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Transaction.destination_address)
}
inline void Transaction::set_destination_address(const char* value) {
  set_has_destination_address();
  destination_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Transaction.destination_address)
}
inline void Transaction::set_destination_address(const char* value, size_t size) {
  set_has_destination_address();
  destination_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Transaction.destination_address)
}
inline ::std::string* Transaction::mutable_destination_address() {
  set_has_destination_address();
  // @@protoc_insertion_point(field_mutable:bubi.Transaction.destination_address)
  return destination_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Transaction::release_destination_address() {
  clear_has_destination_address();
  return destination_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_allocated_destination_address(::std::string* destination_address) {
  if (destination_address != NULL) {
    set_has_destination_address();
  } else {
    clear_has_destination_address();
  }
  destination_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destination_address);
  // @@protoc_insertion_point(field_set_allocated:bubi.Transaction.destination_address)
}

// optional double payment_amount = 3;
inline bool Transaction::has_payment_amount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Transaction::set_has_payment_amount() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Transaction::clear_has_payment_amount() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Transaction::clear_payment_amount() {
  payment_amount_ = 0;
  clear_has_payment_amount();
}
inline double Transaction::payment_amount() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.payment_amount)
  return payment_amount_;
}
inline void Transaction::set_payment_amount(double value) {
  set_has_payment_amount();
  payment_amount_ = value;
  // @@protoc_insertion_point(field_set:bubi.Transaction.payment_amount)
}

// required uint32 source_previous_ledger_seq = 4;
inline bool Transaction::has_source_previous_ledger_seq() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Transaction::set_has_source_previous_ledger_seq() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Transaction::clear_has_source_previous_ledger_seq() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Transaction::clear_source_previous_ledger_seq() {
  source_previous_ledger_seq_ = 0u;
  clear_has_source_previous_ledger_seq();
}
inline ::google::protobuf::uint32 Transaction::source_previous_ledger_seq() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.source_previous_ledger_seq)
  return source_previous_ledger_seq_;
}
inline void Transaction::set_source_previous_ledger_seq(::google::protobuf::uint32 value) {
  set_has_source_previous_ledger_seq();
  source_previous_ledger_seq_ = value;
  // @@protoc_insertion_point(field_set:bubi.Transaction.source_previous_ledger_seq)
}

// required string source_previous_tx_hash = 5;
inline bool Transaction::has_source_previous_tx_hash() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Transaction::set_has_source_previous_tx_hash() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Transaction::clear_has_source_previous_tx_hash() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Transaction::clear_source_previous_tx_hash() {
  source_previous_tx_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_source_previous_tx_hash();
}
inline const ::std::string& Transaction::source_previous_tx_hash() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.source_previous_tx_hash)
  return source_previous_tx_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_source_previous_tx_hash(const ::std::string& value) {
  set_has_source_previous_tx_hash();
  source_previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Transaction.source_previous_tx_hash)
}
inline void Transaction::set_source_previous_tx_hash(const char* value) {
  set_has_source_previous_tx_hash();
  source_previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Transaction.source_previous_tx_hash)
}
inline void Transaction::set_source_previous_tx_hash(const char* value, size_t size) {
  set_has_source_previous_tx_hash();
  source_previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Transaction.source_previous_tx_hash)
}
inline ::std::string* Transaction::mutable_source_previous_tx_hash() {
  set_has_source_previous_tx_hash();
  // @@protoc_insertion_point(field_mutable:bubi.Transaction.source_previous_tx_hash)
  return source_previous_tx_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Transaction::release_source_previous_tx_hash() {
  clear_has_source_previous_tx_hash();
  return source_previous_tx_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_allocated_source_previous_tx_hash(::std::string* source_previous_tx_hash) {
  if (source_previous_tx_hash != NULL) {
    set_has_source_previous_tx_hash();
  } else {
    clear_has_source_previous_tx_hash();
  }
  source_previous_tx_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_previous_tx_hash);
  // @@protoc_insertion_point(field_set_allocated:bubi.Transaction.source_previous_tx_hash)
}

// required uint32 destination_previous_ledger_seq = 6;
inline bool Transaction::has_destination_previous_ledger_seq() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Transaction::set_has_destination_previous_ledger_seq() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Transaction::clear_has_destination_previous_ledger_seq() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Transaction::clear_destination_previous_ledger_seq() {
  destination_previous_ledger_seq_ = 0u;
  clear_has_destination_previous_ledger_seq();
}
inline ::google::protobuf::uint32 Transaction::destination_previous_ledger_seq() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.destination_previous_ledger_seq)
  return destination_previous_ledger_seq_;
}
inline void Transaction::set_destination_previous_ledger_seq(::google::protobuf::uint32 value) {
  set_has_destination_previous_ledger_seq();
  destination_previous_ledger_seq_ = value;
  // @@protoc_insertion_point(field_set:bubi.Transaction.destination_previous_ledger_seq)
}

// required string destination_previous_tx_hash = 7;
inline bool Transaction::has_destination_previous_tx_hash() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Transaction::set_has_destination_previous_tx_hash() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Transaction::clear_has_destination_previous_tx_hash() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Transaction::clear_destination_previous_tx_hash() {
  destination_previous_tx_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_destination_previous_tx_hash();
}
inline const ::std::string& Transaction::destination_previous_tx_hash() const {
  // @@protoc_insertion_point(field_get:bubi.Transaction.destination_previous_tx_hash)
  return destination_previous_tx_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_destination_previous_tx_hash(const ::std::string& value) {
  set_has_destination_previous_tx_hash();
  destination_previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Transaction.destination_previous_tx_hash)
}
inline void Transaction::set_destination_previous_tx_hash(const char* value) {
  set_has_destination_previous_tx_hash();
  destination_previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Transaction.destination_previous_tx_hash)
}
inline void Transaction::set_destination_previous_tx_hash(const char* value, size_t size) {
  set_has_destination_previous_tx_hash();
  destination_previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Transaction.destination_previous_tx_hash)
}
inline ::std::string* Transaction::mutable_destination_previous_tx_hash() {
  set_has_destination_previous_tx_hash();
  // @@protoc_insertion_point(field_mutable:bubi.Transaction.destination_previous_tx_hash)
  return destination_previous_tx_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Transaction::release_destination_previous_tx_hash() {
  clear_has_destination_previous_tx_hash();
  return destination_previous_tx_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_allocated_destination_previous_tx_hash(::std::string* destination_previous_tx_hash) {
  if (destination_previous_tx_hash != NULL) {
    set_has_destination_previous_tx_hash();
  } else {
    clear_has_destination_previous_tx_hash();
  }
  destination_previous_tx_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destination_previous_tx_hash);
  // @@protoc_insertion_point(field_set_allocated:bubi.Transaction.destination_previous_tx_hash)
}

// -------------------------------------------------------------------

// Account

// required string account_address = 1;
inline bool Account::has_account_address() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Account::set_has_account_address() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Account::clear_has_account_address() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Account::clear_account_address() {
  account_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_account_address();
}
inline const ::std::string& Account::account_address() const {
  // @@protoc_insertion_point(field_get:bubi.Account.account_address)
  return account_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Account::set_account_address(const ::std::string& value) {
  set_has_account_address();
  account_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Account.account_address)
}
inline void Account::set_account_address(const char* value) {
  set_has_account_address();
  account_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Account.account_address)
}
inline void Account::set_account_address(const char* value, size_t size) {
  set_has_account_address();
  account_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Account.account_address)
}
inline ::std::string* Account::mutable_account_address() {
  set_has_account_address();
  // @@protoc_insertion_point(field_mutable:bubi.Account.account_address)
  return account_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Account::release_account_address() {
  clear_has_account_address();
  return account_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Account::set_allocated_account_address(::std::string* account_address) {
  if (account_address != NULL) {
    set_has_account_address();
  } else {
    clear_has_account_address();
  }
  account_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_address);
  // @@protoc_insertion_point(field_set_allocated:bubi.Account.account_address)
}

// required double account_balance = 2;
inline bool Account::has_account_balance() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Account::set_has_account_balance() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Account::clear_has_account_balance() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Account::clear_account_balance() {
  account_balance_ = 0;
  clear_has_account_balance();
}
inline double Account::account_balance() const {
  // @@protoc_insertion_point(field_get:bubi.Account.account_balance)
  return account_balance_;
}
inline void Account::set_account_balance(double value) {
  set_has_account_balance();
  account_balance_ = value;
  // @@protoc_insertion_point(field_set:bubi.Account.account_balance)
}

// required uint32 previous_ledger_seq = 3;
inline bool Account::has_previous_ledger_seq() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Account::set_has_previous_ledger_seq() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Account::clear_has_previous_ledger_seq() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Account::clear_previous_ledger_seq() {
  previous_ledger_seq_ = 0u;
  clear_has_previous_ledger_seq();
}
inline ::google::protobuf::uint32 Account::previous_ledger_seq() const {
  // @@protoc_insertion_point(field_get:bubi.Account.previous_ledger_seq)
  return previous_ledger_seq_;
}
inline void Account::set_previous_ledger_seq(::google::protobuf::uint32 value) {
  set_has_previous_ledger_seq();
  previous_ledger_seq_ = value;
  // @@protoc_insertion_point(field_set:bubi.Account.previous_ledger_seq)
}

// required string previous_tx_hash = 4;
inline bool Account::has_previous_tx_hash() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Account::set_has_previous_tx_hash() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Account::clear_has_previous_tx_hash() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Account::clear_previous_tx_hash() {
  previous_tx_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_previous_tx_hash();
}
inline const ::std::string& Account::previous_tx_hash() const {
  // @@protoc_insertion_point(field_get:bubi.Account.previous_tx_hash)
  return previous_tx_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Account::set_previous_tx_hash(const ::std::string& value) {
  set_has_previous_tx_hash();
  previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bubi.Account.previous_tx_hash)
}
inline void Account::set_previous_tx_hash(const char* value) {
  set_has_previous_tx_hash();
  previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bubi.Account.previous_tx_hash)
}
inline void Account::set_previous_tx_hash(const char* value, size_t size) {
  set_has_previous_tx_hash();
  previous_tx_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bubi.Account.previous_tx_hash)
}
inline ::std::string* Account::mutable_previous_tx_hash() {
  set_has_previous_tx_hash();
  // @@protoc_insertion_point(field_mutable:bubi.Account.previous_tx_hash)
  return previous_tx_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Account::release_previous_tx_hash() {
  clear_has_previous_tx_hash();
  return previous_tx_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Account::set_allocated_previous_tx_hash(::std::string* previous_tx_hash) {
  if (previous_tx_hash != NULL) {
    set_has_previous_tx_hash();
  } else {
    clear_has_previous_tx_hash();
  }
  previous_tx_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), previous_tx_hash);
  // @@protoc_insertion_point(field_set_allocated:bubi.Account.previous_tx_hash)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace bubi

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_transaction_2eproto__INCLUDED
