// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bubi.proto

#ifndef PROTOBUF_bubi_2eproto__INCLUDED
#define PROTOBUF_bubi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protocol {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_bubi_2eproto();
void protobuf_AssignDesc_bubi_2eproto();
void protobuf_ShutdownFile_bubi_2eproto();

class bubiMsgHeader;
class bubiMsg;

// ===================================================================

class bubiMsgHeader : public ::google::protobuf::Message {
 public:
  bubiMsgHeader();
  virtual ~bubiMsgHeader();

  bubiMsgHeader(const bubiMsgHeader& from);

  inline bubiMsgHeader& operator=(const bubiMsgHeader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const bubiMsgHeader& default_instance();

  void Swap(bubiMsgHeader* other);

  // implements Message ----------------------------------------------

  inline bubiMsgHeader* New() const { return New(NULL); }

  bubiMsgHeader* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const bubiMsgHeader& from);
  void MergeFrom(const bubiMsgHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(bubiMsgHeader* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string command = 1;
  bool has_command() const;
  void clear_command();
  static const int kCommandFieldNumber = 1;
  const ::std::string& command() const;
  void set_command(const ::std::string& value);
  void set_command(const char* value);
  void set_command(const char* value, size_t size);
  ::std::string* mutable_command();
  ::std::string* release_command();
  void set_allocated_command(::std::string* command);

  // required uint32 msgSize = 2;
  bool has_msgsize() const;
  void clear_msgsize();
  static const int kMsgSizeFieldNumber = 2;
  ::google::protobuf::uint32 msgsize() const;
  void set_msgsize(::google::protobuf::uint32 value);

  // optional uint32 checkSum = 3;
  bool has_checksum() const;
  void clear_checksum();
  static const int kCheckSumFieldNumber = 3;
  ::google::protobuf::uint32 checksum() const;
  void set_checksum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:protocol.bubiMsgHeader)
 private:
  inline void set_has_command();
  inline void clear_has_command();
  inline void set_has_msgsize();
  inline void clear_has_msgsize();
  inline void set_has_checksum();
  inline void clear_has_checksum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr command_;
  ::google::protobuf::uint32 msgsize_;
  ::google::protobuf::uint32 checksum_;
  friend void  protobuf_AddDesc_bubi_2eproto();
  friend void protobuf_AssignDesc_bubi_2eproto();
  friend void protobuf_ShutdownFile_bubi_2eproto();

  void InitAsDefaultInstance();
  static bubiMsgHeader* default_instance_;
};
// -------------------------------------------------------------------

class bubiMsg : public ::google::protobuf::Message {
 public:
  bubiMsg();
  virtual ~bubiMsg();

  bubiMsg(const bubiMsg& from);

  inline bubiMsg& operator=(const bubiMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const bubiMsg& default_instance();

  void Swap(bubiMsg* other);

  // implements Message ----------------------------------------------

  inline bubiMsg* New() const { return New(NULL); }

  bubiMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const bubiMsg& from);
  void MergeFrom(const bubiMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(bubiMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .protocol.bubiMsgHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::protocol::bubiMsgHeader& header() const;
  ::protocol::bubiMsgHeader* mutable_header();
  ::protocol::bubiMsgHeader* release_header();
  void set_allocated_header(::protocol::bubiMsgHeader* header);

  // required string data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const char* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:protocol.bubiMsg)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_data();
  inline void clear_has_data();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::protocol::bubiMsgHeader* header_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  friend void  protobuf_AddDesc_bubi_2eproto();
  friend void protobuf_AssignDesc_bubi_2eproto();
  friend void protobuf_ShutdownFile_bubi_2eproto();

  void InitAsDefaultInstance();
  static bubiMsg* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// bubiMsgHeader

// required string command = 1;
inline bool bubiMsgHeader::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void bubiMsgHeader::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
inline void bubiMsgHeader::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void bubiMsgHeader::clear_command() {
  command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_command();
}
inline const ::std::string& bubiMsgHeader::command() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.command)
  return command_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void bubiMsgHeader::set_command(const ::std::string& value) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.command)
}
inline void bubiMsgHeader::set_command(const char* value) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.bubiMsgHeader.command)
}
inline void bubiMsgHeader::set_command(const char* value, size_t size) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.bubiMsgHeader.command)
}
inline ::std::string* bubiMsgHeader::mutable_command() {
  set_has_command();
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsgHeader.command)
  return command_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* bubiMsgHeader::release_command() {
  clear_has_command();
  return command_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void bubiMsgHeader::set_allocated_command(::std::string* command) {
  if (command != NULL) {
    set_has_command();
  } else {
    clear_has_command();
  }
  command_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), command);
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsgHeader.command)
}

// required uint32 msgSize = 2;
inline bool bubiMsgHeader::has_msgsize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void bubiMsgHeader::set_has_msgsize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void bubiMsgHeader::clear_has_msgsize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void bubiMsgHeader::clear_msgsize() {
  msgsize_ = 0u;
  clear_has_msgsize();
}
inline ::google::protobuf::uint32 bubiMsgHeader::msgsize() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.msgSize)
  return msgsize_;
}
inline void bubiMsgHeader::set_msgsize(::google::protobuf::uint32 value) {
  set_has_msgsize();
  msgsize_ = value;
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.msgSize)
}

// optional uint32 checkSum = 3;
inline bool bubiMsgHeader::has_checksum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void bubiMsgHeader::set_has_checksum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void bubiMsgHeader::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void bubiMsgHeader::clear_checksum() {
  checksum_ = 0u;
  clear_has_checksum();
}
inline ::google::protobuf::uint32 bubiMsgHeader::checksum() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.checkSum)
  return checksum_;
}
inline void bubiMsgHeader::set_checksum(::google::protobuf::uint32 value) {
  set_has_checksum();
  checksum_ = value;
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.checkSum)
}

// -------------------------------------------------------------------

// bubiMsg

// required .protocol.bubiMsgHeader header = 1;
inline bool bubiMsg::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void bubiMsg::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void bubiMsg::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void bubiMsg::clear_header() {
  if (header_ != NULL) header_->::protocol::bubiMsgHeader::Clear();
  clear_has_header();
}
inline const ::protocol::bubiMsgHeader& bubiMsg::header() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsg.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::protocol::bubiMsgHeader* bubiMsg::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::protocol::bubiMsgHeader;
  }
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsg.header)
  return header_;
}
inline ::protocol::bubiMsgHeader* bubiMsg::release_header() {
  clear_has_header();
  ::protocol::bubiMsgHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline void bubiMsg::set_allocated_header(::protocol::bubiMsgHeader* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsg.header)
}

// required string data = 2;
inline bool bubiMsg::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void bubiMsg::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void bubiMsg::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void bubiMsg::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& bubiMsg::data() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsg.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void bubiMsg::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.bubiMsg.data)
}
inline void bubiMsg::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.bubiMsg.data)
}
inline void bubiMsg::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.bubiMsg.data)
}
inline ::std::string* bubiMsg::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsg.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* bubiMsg::release_data() {
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void bubiMsg::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsg.data)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_bubi_2eproto__INCLUDED
