// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bubi.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "bubi.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocol {

namespace {

const ::google::protobuf::Descriptor* bubiMsgHeader_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  bubiMsgHeader_reflection_ = NULL;
const ::google::protobuf::Descriptor* bubiMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  bubiMsg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_bubi_2eproto() {
  protobuf_AddDesc_bubi_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "bubi.proto");
  GOOGLE_CHECK(file != NULL);
  bubiMsgHeader_descriptor_ = file->message_type(0);
  static const int bubiMsgHeader_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsgHeader, command_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsgHeader, msgsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsgHeader, checksum_),
  };
  bubiMsgHeader_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      bubiMsgHeader_descriptor_,
      bubiMsgHeader::default_instance_,
      bubiMsgHeader_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsgHeader, _has_bits_[0]),
      -1,
      -1,
      sizeof(bubiMsgHeader),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsgHeader, _internal_metadata_),
      -1);
  bubiMsg_descriptor_ = file->message_type(1);
  static const int bubiMsg_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsg, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsg, data_),
  };
  bubiMsg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      bubiMsg_descriptor_,
      bubiMsg::default_instance_,
      bubiMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsg, _has_bits_[0]),
      -1,
      -1,
      sizeof(bubiMsg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(bubiMsg, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_bubi_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      bubiMsgHeader_descriptor_, &bubiMsgHeader::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      bubiMsg_descriptor_, &bubiMsg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_bubi_2eproto() {
  delete bubiMsgHeader::default_instance_;
  delete bubiMsgHeader_reflection_;
  delete bubiMsg::default_instance_;
  delete bubiMsg_reflection_;
}

void protobuf_AddDesc_bubi_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nbubi.proto\022\010protocol\"C\n\rbubiMsgHeader\022"
    "\017\n\007command\030\001 \002(\t\022\017\n\007msgSize\030\002 \002(\r\022\020\n\010che"
    "ckSum\030\003 \001(\r\"@\n\007bubiMsg\022\'\n\006header\030\001 \002(\0132\027"
    ".protocol.bubiMsgHeader\022\014\n\004data\030\002 \002(\t", 157);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bubi.proto", &protobuf_RegisterTypes);
  bubiMsgHeader::default_instance_ = new bubiMsgHeader();
  bubiMsg::default_instance_ = new bubiMsg();
  bubiMsgHeader::default_instance_->InitAsDefaultInstance();
  bubiMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_bubi_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_bubi_2eproto {
  StaticDescriptorInitializer_bubi_2eproto() {
    protobuf_AddDesc_bubi_2eproto();
  }
} static_descriptor_initializer_bubi_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int bubiMsgHeader::kCommandFieldNumber;
const int bubiMsgHeader::kMsgSizeFieldNumber;
const int bubiMsgHeader::kCheckSumFieldNumber;
#endif  // !_MSC_VER

bubiMsgHeader::bubiMsgHeader()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.bubiMsgHeader)
}

void bubiMsgHeader::InitAsDefaultInstance() {
}

bubiMsgHeader::bubiMsgHeader(const bubiMsgHeader& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.bubiMsgHeader)
}

void bubiMsgHeader::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgsize_ = 0u;
  checksum_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bubiMsgHeader::~bubiMsgHeader() {
  // @@protoc_insertion_point(destructor:protocol.bubiMsgHeader)
  SharedDtor();
}

void bubiMsgHeader::SharedDtor() {
  command_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void bubiMsgHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* bubiMsgHeader::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return bubiMsgHeader_descriptor_;
}

const bubiMsgHeader& bubiMsgHeader::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_bubi_2eproto();
  return *default_instance_;
}

bubiMsgHeader* bubiMsgHeader::default_instance_ = NULL;

bubiMsgHeader* bubiMsgHeader::New(::google::protobuf::Arena* arena) const {
  bubiMsgHeader* n = new bubiMsgHeader;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void bubiMsgHeader::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<bubiMsgHeader*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(msgsize_, checksum_);
    if (has_command()) {
      command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool bubiMsgHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.bubiMsgHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string command = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->command().data(), this->command().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protocol.bubiMsgHeader.command");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_msgSize;
        break;
      }

      // required uint32 msgSize = 2;
      case 2: {
        if (tag == 16) {
         parse_msgSize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &msgsize_)));
          set_has_msgsize();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_checkSum;
        break;
      }

      // optional uint32 checkSum = 3;
      case 3: {
        if (tag == 24) {
         parse_checkSum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &checksum_)));
          set_has_checksum();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.bubiMsgHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.bubiMsgHeader)
  return false;
#undef DO_
}

void bubiMsgHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.bubiMsgHeader)
  // required string command = 1;
  if (has_command()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->command().data(), this->command().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protocol.bubiMsgHeader.command");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->command(), output);
  }

  // required uint32 msgSize = 2;
  if (has_msgsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->msgsize(), output);
  }

  // optional uint32 checkSum = 3;
  if (has_checksum()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->checksum(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.bubiMsgHeader)
}

::google::protobuf::uint8* bubiMsgHeader::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.bubiMsgHeader)
  // required string command = 1;
  if (has_command()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->command().data(), this->command().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protocol.bubiMsgHeader.command");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->command(), target);
  }

  // required uint32 msgSize = 2;
  if (has_msgsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->msgsize(), target);
  }

  // optional uint32 checkSum = 3;
  if (has_checksum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->checksum(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.bubiMsgHeader)
  return target;
}

int bubiMsgHeader::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_command()) {
    // required string command = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->command());
  }

  if (has_msgsize()) {
    // required uint32 msgSize = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->msgsize());
  }

  return total_size;
}
int bubiMsgHeader::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string command = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->command());

    // required uint32 msgSize = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->msgsize());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional uint32 checkSum = 3;
  if (has_checksum()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->checksum());
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void bubiMsgHeader::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const bubiMsgHeader* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const bubiMsgHeader*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void bubiMsgHeader::MergeFrom(const bubiMsgHeader& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_command()) {
      set_has_command();
      command_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_);
    }
    if (from.has_msgsize()) {
      set_msgsize(from.msgsize());
    }
    if (from.has_checksum()) {
      set_checksum(from.checksum());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void bubiMsgHeader::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void bubiMsgHeader::CopyFrom(const bubiMsgHeader& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool bubiMsgHeader::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void bubiMsgHeader::Swap(bubiMsgHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void bubiMsgHeader::InternalSwap(bubiMsgHeader* other) {
  command_.Swap(&other->command_);
  std::swap(msgsize_, other->msgsize_);
  std::swap(checksum_, other->checksum_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata bubiMsgHeader::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = bubiMsgHeader_descriptor_;
  metadata.reflection = bubiMsgHeader_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// bubiMsgHeader

// required string command = 1;
 bool bubiMsgHeader::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void bubiMsgHeader::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
 void bubiMsgHeader::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
 void bubiMsgHeader::clear_command() {
  command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_command();
}
 const ::std::string& bubiMsgHeader::command() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.command)
  return command_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void bubiMsgHeader::set_command(const ::std::string& value) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.command)
}
 void bubiMsgHeader::set_command(const char* value) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.bubiMsgHeader.command)
}
 void bubiMsgHeader::set_command(const char* value, size_t size) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.bubiMsgHeader.command)
}
 ::std::string* bubiMsgHeader::mutable_command() {
  set_has_command();
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsgHeader.command)
  return command_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* bubiMsgHeader::release_command() {
  clear_has_command();
  return command_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void bubiMsgHeader::set_allocated_command(::std::string* command) {
  if (command != NULL) {
    set_has_command();
  } else {
    clear_has_command();
  }
  command_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), command);
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsgHeader.command)
}

// required uint32 msgSize = 2;
 bool bubiMsgHeader::has_msgsize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
 void bubiMsgHeader::set_has_msgsize() {
  _has_bits_[0] |= 0x00000002u;
}
 void bubiMsgHeader::clear_has_msgsize() {
  _has_bits_[0] &= ~0x00000002u;
}
 void bubiMsgHeader::clear_msgsize() {
  msgsize_ = 0u;
  clear_has_msgsize();
}
 ::google::protobuf::uint32 bubiMsgHeader::msgsize() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.msgSize)
  return msgsize_;
}
 void bubiMsgHeader::set_msgsize(::google::protobuf::uint32 value) {
  set_has_msgsize();
  msgsize_ = value;
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.msgSize)
}

// optional uint32 checkSum = 3;
 bool bubiMsgHeader::has_checksum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
 void bubiMsgHeader::set_has_checksum() {
  _has_bits_[0] |= 0x00000004u;
}
 void bubiMsgHeader::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000004u;
}
 void bubiMsgHeader::clear_checksum() {
  checksum_ = 0u;
  clear_has_checksum();
}
 ::google::protobuf::uint32 bubiMsgHeader::checksum() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsgHeader.checkSum)
  return checksum_;
}
 void bubiMsgHeader::set_checksum(::google::protobuf::uint32 value) {
  set_has_checksum();
  checksum_ = value;
  // @@protoc_insertion_point(field_set:protocol.bubiMsgHeader.checkSum)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int bubiMsg::kHeaderFieldNumber;
const int bubiMsg::kDataFieldNumber;
#endif  // !_MSC_VER

bubiMsg::bubiMsg()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.bubiMsg)
}

void bubiMsg::InitAsDefaultInstance() {
  header_ = const_cast< ::protocol::bubiMsgHeader*>(&::protocol::bubiMsgHeader::default_instance());
}

bubiMsg::bubiMsg(const bubiMsg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.bubiMsg)
}

void bubiMsg::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  header_ = NULL;
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bubiMsg::~bubiMsg() {
  // @@protoc_insertion_point(destructor:protocol.bubiMsg)
  SharedDtor();
}

void bubiMsg::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete header_;
  }
}

void bubiMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* bubiMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return bubiMsg_descriptor_;
}

const bubiMsg& bubiMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_bubi_2eproto();
  return *default_instance_;
}

bubiMsg* bubiMsg::default_instance_ = NULL;

bubiMsg* bubiMsg::New(::google::protobuf::Arena* arena) const {
  bubiMsg* n = new bubiMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void bubiMsg::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_header()) {
      if (header_ != NULL) header_->::protocol::bubiMsgHeader::Clear();
    }
    if (has_data()) {
      data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool bubiMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.bubiMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .protocol.bubiMsgHeader header = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_data;
        break;
      }

      // required string data = 2;
      case 2: {
        if (tag == 18) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->data().data(), this->data().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "protocol.bubiMsg.data");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.bubiMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.bubiMsg)
  return false;
#undef DO_
}

void bubiMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.bubiMsg)
  // required .protocol.bubiMsgHeader header = 1;
  if (has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->header_, output);
  }

  // required string data = 2;
  if (has_data()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protocol.bubiMsg.data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.bubiMsg)
}

::google::protobuf::uint8* bubiMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.bubiMsg)
  // required .protocol.bubiMsgHeader header = 1;
  if (has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->header_, target);
  }

  // required string data = 2;
  if (has_data()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "protocol.bubiMsg.data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.bubiMsg)
  return target;
}

int bubiMsg::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_header()) {
    // required .protocol.bubiMsgHeader header = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->header_);
  }

  if (has_data()) {
    // required string data = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->data());
  }

  return total_size;
}
int bubiMsg::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .protocol.bubiMsgHeader header = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->header_);

    // required string data = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->data());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void bubiMsg::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const bubiMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const bubiMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void bubiMsg::MergeFrom(const bubiMsg& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_header()) {
      mutable_header()->::protocol::bubiMsgHeader::MergeFrom(from.header());
    }
    if (from.has_data()) {
      set_has_data();
      data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void bubiMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void bubiMsg::CopyFrom(const bubiMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool bubiMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_header()) {
    if (!this->header_->IsInitialized()) return false;
  }
  return true;
}

void bubiMsg::Swap(bubiMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void bubiMsg::InternalSwap(bubiMsg* other) {
  std::swap(header_, other->header_);
  data_.Swap(&other->data_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata bubiMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = bubiMsg_descriptor_;
  metadata.reflection = bubiMsg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// bubiMsg

// required .protocol.bubiMsgHeader header = 1;
 bool bubiMsg::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void bubiMsg::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
 void bubiMsg::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
 void bubiMsg::clear_header() {
  if (header_ != NULL) header_->::protocol::bubiMsgHeader::Clear();
  clear_has_header();
}
 const ::protocol::bubiMsgHeader& bubiMsg::header() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsg.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
 ::protocol::bubiMsgHeader* bubiMsg::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::protocol::bubiMsgHeader;
  }
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsg.header)
  return header_;
}
 ::protocol::bubiMsgHeader* bubiMsg::release_header() {
  clear_has_header();
  ::protocol::bubiMsgHeader* temp = header_;
  header_ = NULL;
  return temp;
}
 void bubiMsg::set_allocated_header(::protocol::bubiMsgHeader* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsg.header)
}

// required string data = 2;
 bool bubiMsg::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
 void bubiMsg::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
 void bubiMsg::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
 void bubiMsg::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
 const ::std::string& bubiMsg::data() const {
  // @@protoc_insertion_point(field_get:protocol.bubiMsg.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void bubiMsg::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.bubiMsg.data)
}
 void bubiMsg::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.bubiMsg.data)
}
 void bubiMsg::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.bubiMsg.data)
}
 ::std::string* bubiMsg::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:protocol.bubiMsg.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* bubiMsg::release_data() {
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void bubiMsg::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:protocol.bubiMsg.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)
